name: Continuous Testing and Publication

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-js-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/checkout@v7
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions
      - name: Validate JS
        uses: ./actions/js/validate
        with:
          node-version: '20.x'
          skip-eslint: 'true'
      - name: Run JS tests
        uses: ./actions/js/test
        with:
          node-version: ${{ matrix.node-version }}

  publish:
    needs: run-js-tests
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/checkout@v7
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions
      - name: Publish JS release
        uses: ./actions/js/publish
        with:
          node-version: 20.x
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          verify-tests: 'false'
